spring:
  lifecycle:
    timeout-per-shutdown-phase: 120s
  profiles:
    include: app,dev
  datasource:
    url: jdbc:mysql://localhost:3306/jxc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    hikari:
      keepalive-time: 60000
      max-lifetime: 1500000
      maximum-pool-size: 200
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.flyemu.share.hibernate.SharePhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  sqltoy:
    sql-resources-dir: classpath:/sqltoy
    debug: true
  data:
    redis:
      repositories:
        enabled: false
      url: "redis://127.0.0.1:6379"
      database: 5
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  cache:
    redis:
      key-prefix: jxc_
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 30
server:
  shutdown: graceful
  tomcat:
    basedir:

app:
  upload-root:
  #  阿里短信服务
  aliyun:
    accessKeyId:
    accessKeySecret:
    sms:
      signature: 纷析云
      template-code:
        verification: SMS_175580136
        register: SMS_217436843

