server:
  port: 8410

spring:
  data:
    redis:
      database: 7
  cache:
    redis:
      key-prefix: i_c_m_
      cache-null-values: false

sa-token:
  token-name: i-c-m-token

aliyun:
  accessKeyId:
  accessKeySecret:
  bucketName:

